### ISSUE TITLE
Remove dependency for Requests package

### ISSUE THREAD

**Issue by RihanWu** [RihanWu/vocabtool#2]
@StephDC In my opinion, we need to compare the performance difference between using standard libraries and third-party libraries. What do you think?

**Comment by StephDC** [comment]
The tested result is that both of them have similar performance, but another interesting thing I noticed is that the Requests package is automatically decoding the web page by looking at the HTTP Header Content-Type, and fallback to ISO-8859-1 but not UTF-8 if such information was not present such as in http://worm.hanfucw.com/encodingText.txt and http://hanfucw.com (my websites)

**Comment by StephDC** [comment]
Actually even if you still prefer just to use the Requests package, I highly recommend you to personalize the HTTP request before sending it out as you did in your code.
Adding a User-Agent header, and maybe use gzip to save bandwidth would be useful and helpful. To include these all together, the easiest way I can think of is just to use another layer of wrapper, maybe named RequestsRequests.py, to pack requests from the dict/sth or anywhere else in this program before sending it out.

**Comment by RihanWu** [comment]
I prefer to use Requests so that we don't need to worry about decompressing gzip data.
About the headers, how about this?
Put this in base_class.py

``` python
def get(url, **args):
    headers = {"User-Agent": "VocabTool/0.2 \
                (https://github.com/RihanWu/vocabtool)",
               "Accept-Encoding": "gzip, deflate",
               "Accept-Charset": "utf-8"}
    return requests.get(url, headers=headers, **args)

```

Then this in the dict/sth.py

``` python
response = base_class.get(self.base_url + self.word_text)
```

In this case, I get a execution time of about 3 seconds

``` python
from vocabtool import core
from time import time

t_start = time()
word = "test"
result = core.lookup_word(word, "en")
show = ("".join([x.show_no_style() for x in result]))
show = (lambda y: y is not "" and y or "No response")(show)
print(time() - t_start)
```

See: https://github.com/RihanWu/vocabtool/tree/requests_add_headers

**Comment by StephDC** [comment]
That looks great.
btw why not just decode on the fly instead of calling Response.text later? Do you still need any other information from the response?

``` python
def get(url, **args):
    headers = {"User-Agent": "VocabTool/0.2 \
                (https://github.com/RihanWu/vocabtool)",
               "Accept-Encoding": "gzip, deflate",
               "Accept-Charset": "utf-8"}
    result = requests.get(url, headers=headers, **args)
    return result.content.decode(result.apparent_encoding)
```

**Comment by RihanWu** [comment]
Nope, I just forgot to do that(_/ω＼_) 
And we can probably just use `result.text`

**Comment by StephDC** [comment]
We cannot use result.text because it is using Content-Type to determine the encoding, and when it is not present, it would fall back to ISO-8859-1 (Who still use this?). Use apparent_encoding would get better chance to obtain the correct encoding.

**Comment by RihanWu** [comment]
(_/ω＼_)I didn't notice that. I will check the code and return to you ASAP.

**Comment by StephDC** [comment]
Just try to use Request to obtain these and you would know what I mean.
- http://worm.hanfucw.com/encodingText.txt (BIG5 encoded, No charset declaration in header)
- http://hanfucw.com:9676/cgi-bin/big5.tail (Also BIG5 encoded, With charset declaration in header)

``` python
>>> import requests
>>> newReq = requests.get('http://worm/encodingText.txt')
>>> md5(newReq.content)
'154f9086bc183f1d2eb3d340097968fe'
>>> newReq.text
'³o¬O¤@¬qÁc¤¤¤å¦r\n'
>>> newReq = requests.get('http://hanfucw.com:9676/cgi-bin/big5.tail')
>>> md5(newReq.content)
'154f9086bc183f1d2eb3d340097968fe'
>>> newReq.text
'這是一段繁中文字\n'
```

The same content yield different result. Why?

``` python
>>> '³o¬O¤@¬qÁc¤¤¤å¦r\n'.encode('ISO-8859-1').decode('BIG5')
'這是一段繁中文字\n'
```

**Comment by StephDC** [comment]
Another issue with the apparent_encoding only: Sometimes apparent_encoding is None
e.g. http://hanfucw.com:9676/cgi-bin/sjis.tail
But the text is in SHIFT_JIS
There seems to be no exact way to know which encoding is in use... Maybe use header as back-up?
And definitely if the server side has messed up everything, wrong answer would be inevitable.
http://hanfucw.com:9676/cgi-bin/wrongheader.tail

**Comment by StephDC** [comment]
A better solution:

``` python
def get(url, **args):
    headers = {"User-Agent": "VocabTool/0.2 \
                (https://github.com/RihanWu/vocabtool)",
               "Accept-Encoding": "gzip, deflate",
               "Accept-Charset": "utf-8"}
    result = requests.get(url, headers=headers, **args)
    if result.apparent_encoding is not None:
        return result.content.decode(result.apparent_encoding)
    else:
        return result.text
```

**Comment by RihanWu** [comment]
Yes, I am aware of this. Without encoding information, there is no guaranteed method to guess the encoding use.
And also, I agree with the latter solution.
